### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by rhinjard** [azerothcore/mod-npc-enchanter#15]
The module failed to compile in VS2019 with the latest AzerothCore commits.
`
D:\AzerothCore\source\azerothcore-wotlk\modules\mod-npc-enchanter\src\npc_enchanter.cpp(253,19): error C3646: 'PickPhrase': unknown override specifier

D:\AzerothCore\source\azerothcore-wotlk\modules\mod-npc-enchanter\src\npc_enchanter.cpp(253,30): error C2059: syntax error: ')'

D:\AzerothCore\source\azerothcore-wotlk\modules\mod-npc-enchanter\src\npc_enchanter.cpp(254,5): error C2334: unexpected token(s) preceding '{'; skipping apparent function body

D:\AzerothCore\source\azerothcore-wotlk\modules\mod-npc-enchanter\src\npc_enchanter.cpp(1048,43): error C3861: 'PickPhrase': identifier not found
`

**Comment by Helias** [comment]
try with this https://github.com/azerothcore/mod-npc-enchanter/pull/16

**Comment by rhinjard** [comment]
> try with this #16

Thanks, that fixed the issue.
